name: Generate docs for 'search_table.html' template

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
        matrix:
            python-version: [3.8]

        steps:
            - uses: actions/checkout@v1
